# Generated by Django 4.2.4 on 2023-08-30 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostapp', '0006_alter_scan_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
        migrations.AddField(
            model_name='target',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
    ]
