# Generated by Django 4.2.4 on 2023-08-30 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostapp', '0007_scan_pdf_file_target_pdf_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='pdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='pdfs/')),
            ],
        ),
        migrations.RemoveField(
            model_name='scan',
            name='pdf_file',
        ),
        migrations.RemoveField(
            model_name='target',
            name='pdf_file',
        ),
    ]
