# Generated by Django 4.2.4 on 2023-08-31 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostapp', '0008_pdf_remove_scan_pdf_file_remove_target_pdf_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Scantype', models.CharField(max_length=100)),
                ('target', models.URLField(max_length=100)),
                ('Thread_Level', models.CharField(max_length=100)),
                ('openvas_QOD', models.FloatField()),
                ('STatus', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
