# Generated by Django 4.2.4 on 2023-09-01 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostapp', '0010_scan_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='json_file',
            field=models.FileField(blank=True, null=True, upload_to='scans/jsons/'),
        ),
        migrations.AlterField(
            model_name='scan',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
    ]
